INSERT INTO TESTDB.PUBLIC.DOCUMENTO (DOCUMENTO) VALUES ('Cedula de ciudadania' );
INSERT INTO TESTDB.PUBLIC.DOCUMENTO (DOCUMENTO) VALUES ('Pasaporte' );


INSERT INTO TESTDB.PUBLIC.PERSONA
(PRIMER_NOMBRE, SEGUNDO_NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, TELEFONO, DIRECCION, CIUDAD_RESIDENCIA)
VALUES ('JORGE', 'ERICK', 'JAEN', 'LÓPEZ', '0987654321', 'CALLE 1', 'XALAPA');


INSERT INTO TESTDB.PUBLIC.DOCUMENTO_PERSONA
    (PERSONA_ID, DOCUMENTO_ID, NUMERO_DOCUMENTO)
    VALUES (1, 1, 23445322);